# Generated by Django 4.2.30 on 2026-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (URL)')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('price_from', models.IntegerField(blank=True, null=True, verbose_name='Цена от')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (Lucide name)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name'],
            },
        ),
    ]
