# Generated by Django 4.2.30 on 2026-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_experience_cover_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(default='Расскажите о вашем доме — перезвоним в течение 30 минут, ответим на вопросы и согласуем выезд на замер.', verbose_name='Описание'),
        ),
    ]
