# Generated by Django 4.2.30 on 2026-05-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_sitepage_otdelochnye_proizvodstvo_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeafteritem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Пусто — показывать как общий пример на всех страницах.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_items', to='main.sitepage', verbose_name='Страница услуги'),
        ),
    ]
