# Generated by Django 4.2.30 on 2026-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_beforeafteritem_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Можно оставить пустым: на сайте будет показано только фото.', max_length=200, verbose_name='Название (необязательно)'),
        ),
    ]
