# Generated by Django 4.2.30 on 2026-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_portfolioproject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='direct_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Целевой'), ('PAID', 'Оплачен'), ('CANCELLED', 'Нецелевой'), ('SPAM', 'Спам')], default='IN_PROGRESS', help_text='Меняется из письма кнопками: целевой, нецелевой, спам, оплачен.', max_length=16, verbose_name='Статус для CSV Директа'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='direct_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Статус CSV обновлён'),
        ),
    ]
