# Generated by Django 4.2.30 on 2026-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_contactlead_direct_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.yandex.ru', max_length=120, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_login',
            field=models.EmailField(blank=True, help_text='Например morozov.diimas39@yandex.ru. Если пусто — берётся EMAIL_HOST_USER из окружения.', max_length=254, verbose_name='Логин SMTP'),
        ),
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Пароль приложения из Яндекс ID. Хранится в базе как обычная строка.', max_length=255, verbose_name='Пароль приложения SMTP'),
        ),
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='SSL'),
        ),
        migrations.AddField(
            model_name='leademailsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS'),
        ),
        migrations.AlterField(
            model_name='leademailsettings',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Один или несколько адресов — через запятую или с новой строки. Пока поле пустое, письма не отправляются.', verbose_name='Email для уведомлений'),
        ),
    ]
