# Generated by Django 4.2.30 on 2026-06-04 07:04

from django.db import migrations, models


def set_reviews_rating(apps, schema_editor):
    ReviewsSection = apps.get_model("main", "ReviewsSection")
    ReviewsSection.objects.update(yandex_rating=4.8)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_restore_working_sender_two_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewssection',
            name='yandex_rating',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=2, verbose_name='Рейтинг (для отображения)'),
        ),
        migrations.RunPython(set_reviews_rating, migrations.RunPython.noop),
    ]
