# Generated by Django 4.2.30 on 2026-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_fix_engineering_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademailsettings',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Адрес, который будет показан в письме как отправитель. Если пусто — используется логин SMTP.', max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='leademailsettings',
            name='smtp_login',
            field=models.EmailField(blank=True, help_text='Технический логин SMTP. Если пусто — берётся EMAIL_HOST_USER из окружения.', max_length=254, verbose_name='Логин SMTP'),
        ),
    ]
