# Generated by Django 4.2.30 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_switch_static_png_fallbacks_to_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesection',
            name='static_image',
            field=models.CharField(blank=True, default='images/team.webp', max_length=200, verbose_name='Фото из static'),
        ),
        migrations.AlterField(
            model_name='service',
            name='static_image',
            field=models.CharField(blank=True, help_text='Например images/quiz/quiz_shlifovka_1776809850085.webp — если нет загрузки.', max_length=200, verbose_name='Фото (static)'),
        ),
    ]
