"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1goiny6m8_ispgx=gabm+g9a50aq$)rkuwgtkd%qr+*p^xh^ip'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.services_processor',
                'main.context_processors.calculator_processor',
                'main.context_processors.portfolio_processor',
                'main.context_processors.experience_processor',
                'main.context_processors.reviews_processor',
                'main.context_processors.work_process_processor',
                'main.context_processors.contact_processor',
                'main.context_processors.faq_processor',
                'main.context_processors.before_after_processor',
                'main.context_processors.blog_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Vite Settings
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "dist"
DJANGO_VITE_MANIFEST_PATH = BASE_DIR / "dist" / ".vite" / "manifest.json"
DJANGO_VITE_DEV_SERVER_PORT = 5173
DJANGO_VITE_DEV_SERVER_HOST = '127.0.0.1'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "ArteMadera",
    "SITE_HEADER": "ArteMadera",
    "SITE_SUBHEADER": "Панель управления",
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "CRM",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Воронка (канбан)",
                        "icon": "view_kanban",
                        "link": "/admin/crm/crmdeal/kanban/",
                    },
                    {
                        "title": "Сделки",
                        "icon": "payments",
                        "link": "/admin/crm/crmdeal/",
                    },
                    {
                        "title": "Контакты",
                        "icon": "contacts",
                        "link": "/admin/crm/crmcontact/",
                    },
                    {
                        "title": "Задачи",
                        "icon": "task_alt",
                        "link": "/admin/crm/crmtask/",
                    },
                    {
                        "title": "Заявки с сайта",
                        "icon": "inbox",
                        "link": "/admin/main/contactlead/",
                    },
                ],
            },
        ],
    },
}
