"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    """Подхватывает переменные из .env в корне проекта (файл в .gitignore)."""
    path = BASE_DIR / ".env"
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, val)


_load_local_env()


def _direct_token_from_dotenv_file() -> str:
    """Только ключ DIRECT_CONVERSIONS_CSV_TOKEN из .env (перебивает пустую переменную в окружении IDE)."""
    path = BASE_DIR / ".env"
    if not path.is_file():
        return ""
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        if key.strip() != "DIRECT_CONVERSIONS_CSV_TOKEN":
            continue
        return val.strip().strip('"').strip("'")
    return ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1goiny6m8_ispgx=gabm+g9a50aq$)rkuwgtkd%qr+*p^xh^ip'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Хосты запроса (Host header). На проде после смены домена: git pull + restart gunicorn.
# Дополнительно без деплоя: переменная DJANGO_ALLOWED_HOSTS=foo.ru,bar.ru (через запятую).
_BASE_ALLOWED_HOSTS = [
    "artemadera.su",
    "www.artemadera.su",
    "artemadera.ru",
    "www.artemadera.ru",
    "localhost",
    "127.0.0.1",
]
_extra_allowed = (os.environ.get("DJANGO_ALLOWED_HOSTS") or "").strip()
if _extra_allowed:
    _from_env = [h.strip() for h in _extra_allowed.split(",") if h.strip()]
    ALLOWED_HOSTS = list(dict.fromkeys(_BASE_ALLOWED_HOSTS + _from_env))
else:
    ALLOWED_HOSTS = list(_BASE_ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.services_processor',
                'main.context_processors.calculator_processor',
                'main.context_processors.portfolio_processor',
                'main.context_processors.experience_processor',
                'main.context_processors.reviews_processor',
                'main.context_processors.work_process_processor',
                'main.context_processors.contact_processor',
                'main.context_processors.faq_processor',
                'main.context_processors.before_after_processor',
                'main.context_processors.blog_processor',
                'main.context_processors.site_page_processor',
                'main.context_processors.home_quiz_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Сюда collectstatic кладёт статику всех приложений (в т.ч. admin + unfold). WhiteNoise отдаёт с диска.
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Отдавать загрузки через Django, если nginx не настроен (демо на artemadera.su)
SERVE_MEDIA = True

# Токен для GET /export/yandex-direct-conversions.csv
# Приоритет: непустой env → значение из .env → при DEBUG дефолт (на проде выставьте env / Secrets!)
_env_direct = (os.environ.get("DIRECT_CONVERSIONS_CSV_TOKEN") or "").strip()
_file_direct = _direct_token_from_dotenv_file().strip()
DIRECT_CONVERSIONS_CSV_TOKEN = _env_direct or _file_direct or ("Qwerty22456" if DEBUG else "")

# Django Vite Settings
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "dist"
DJANGO_VITE_MANIFEST_PATH = BASE_DIR / "dist" / ".vite" / "manifest.json"
DJANGO_VITE_DEV_SERVER_PORT = 5173
DJANGO_VITE_DEV_SERVER_HOST = '127.0.0.1'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Почта: заявки с сайта (send_mail), админка «Уведомления о заявках (email)»
DEFAULT_FROM_EMAIL = (os.environ.get("DEFAULT_FROM_EMAIL") or "").strip() or "noreply@artemadera.su"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = (os.environ.get("EMAIL_HOST") or "").strip()
_raw_port = (os.environ.get("EMAIL_PORT") or "587").strip()
try:
    EMAIL_PORT = int(_raw_port) if _raw_port else 587
except ValueError:
    EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1").strip() not in ("0", "false", "False")
# SMTP без хоста на проде ничего не отправит — падаем в консоль, чтобы письма были видны в логах процесса
if "smtp" in str(EMAIL_BACKEND).lower() and not EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

UNFOLD = {
    "SITE_TITLE": "ArteMadera",
    "SITE_HEADER": "ArteMadera",
    "SITE_SUBHEADER": "Панель управления",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "CRM",
                "icon": "business",
                "collapsible": True,
                "items": [
                    {
                        "title": "Воронка",
                        "icon": "view_kanban",
                        "link": "/admin/crm/crmdeal/kanban/",
                    },
                    {
                        "title": "Сделки",
                        "icon": "payments",
                        "link": "/admin/crm/crmdeal/",
                    },
                    {
                        "title": "Контакты",
                        "icon": "contacts",
                        "link": "/admin/crm/crmcontact/",
                    },
                    {
                        "title": "Задачи",
                        "icon": "task_alt",
                        "link": "/admin/crm/crmtask/",
                    },
                    {
                        "title": "Заявки с сайта",
                        "icon": "inbox",
                        "link": "/admin/main/contactlead/",
                    },
                    {
                        "title": "Почта: уведомления о заявках",
                        "icon": "mail",
                        "link": "/admin/main/leademailsettings/1/change/",
                    },
                ],
            },
            {
                "title": "Сайт",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Страницы",
                        "icon": "web",
                        "link": "/admin/main/sitepage/",
                    },
                    {
                        "title": "Справочник услуг",
                        "icon": "category",
                        "link": "/admin/main/service/",
                    },
                    {
                        "title": "Калькуляторы и цены",
                        "icon": "calculate",
                        "link": "/admin/main/calculatorprofile/",
                    },
                    {
                        "title": "Квиз на главной — фото",
                        "icon": "photo_library",
                        "link": "/admin/main/homequizsettings/",
                    },
                    {
                        "title": "До / после",
                        "icon": "compare",
                        "link": "/admin/main/beforeafteritem/",
                    },
                    {
                        "title": "Статьи блога",
                        "icon": "article",
                        "link": "/admin/main/blogpost/",
                    },
                    {
                        "title": "Кейсы портфолио (фото)",
                        "icon": "photo_library",
                        "link": "/admin/main/portfolioproject/",
                    },
                    {
                        "title": "Отзывы",
                        "icon": "star",
                        "link": "/admin/main/review/",
                    },
                ],
            },
            {
                "title": "Блоки на страницах",
                "icon": "dashboard",
                "collapsible": True,
                "items": [
                    {
                        "title": "О компании — блок (текст и фото)",
                        "icon": "info",
                        "link": "/admin/main/experiencesection/",
                    },
                    {
                        "title": "О компании — цифры",
                        "icon": "numbers",
                        "link": "/admin/main/experiencestat/",
                    },
                    {
                        "title": "О компании — преимущества",
                        "icon": "verified",
                        "link": "/admin/main/experienceadvantage/",
                    },
                    {
                        "title": "До / после — заголовок",
                        "icon": "title",
                        "link": "/admin/main/beforeaftersection/",
                    },
                    {
                        "title": "Этапы работ — шаги",
                        "icon": "timeline",
                        "link": "/admin/main/workprocessstep/",
                    },
                    {
                        "title": "Этапы — заголовок",
                        "icon": "title",
                        "link": "/admin/main/workprocesssection/",
                    },
                    {
                        "title": "FAQ — вопросы",
                        "icon": "help",
                        "link": "/admin/main/faqitem/",
                    },
                    {
                        "title": "FAQ — заголовок",
                        "icon": "title",
                        "link": "/admin/main/faqsection/",
                    },
                    {
                        "title": "Контакты",
                        "icon": "call",
                        "link": "/admin/main/contactsection/",
                    },
                    {
                        "title": "Заголовок портфолио",
                        "icon": "title",
                        "link": "/admin/main/portfoliosection/",
                    },
                    {
                        "title": "Заголовок отзывов",
                        "icon": "title",
                        "link": "/admin/main/reviewssection/",
                    },
                    {
                        "title": "Заголовок блога",
                        "icon": "title",
                        "link": "/admin/main/blogsection/",
                    },
                ],
            },
            {
                "title": "Служебное",
                "icon": "settings",
                "collapsible": True,
                "items": [
                    {
                        "title": "Слайдер площади",
                        "icon": "tune",
                        "link": "/admin/main/calculatorconfig/",
                    },
                    {
                        "title": "Почта: заявки с форм",
                        "icon": "forward_to_inbox",
                        "link": "/admin/main/leademailsettings/1/change/",
                    },
                ],
            },
        ],
    },
}
